# Generated by Django 2.0.3 on 2018-04-01 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Egg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('egg_code', models.CharField(max_length=20)),
                ('egg_name', models.CharField(max_length=150)),
                ('base_color', models.CharField(max_length=20)),
                ('ornament', models.CharField(max_length=25)),
                ('picture', models.CharField(max_length=50)),
                ('cooked', models.DateTimeField()),
                ('best_before', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
